### ISSUE TITLE
Python 3.5 TensorFlow 1.2 variable scope related error

### ISSUE THREAD

**Issue by shirishr** [jonbruner/generative-adversarial-networks#2]
ValueError: Variable d_w1/Adam_1/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

at line 128: d_trainer_fake = tf.train.AdamOptimizer(0.0003).minimize(d_loss_fake, var_list=d_vars)

**Comment by adeshpande3** [comment]
Try restarting the kernel and running the graph creation code again. One of the key parts of using Tensorflow in Jupyter notebooks is making sure that you're not running parts of the graph/optimizer creation multiple times. This causes issues with scope and reusing.

**Comment by shirishr** [comment]
Adit...that must have been it. Am closing this issue
