### ISSUE TITLE
What should I do if I want to use this to train my own database

### ISSUE THREAD

**Issue by Chen65010445** [jonbruner/generative-adversarial-networks#3]
I have a database which consist of low-dose pictures, how should I train them with this algorithm?

**Comment by adeshpande3** [comment]
You'll need to replace the lines where we call the function _mnist.train.next_batch_. For example, in the line

`real_image_batch = mnist.train.next_batch(batch_size)[0].reshape([batch_size, 28, 28, 1])`

you'll need to create your own python function that basically returns a random subset of your dataset. For example, if you have 25,000 images that are each 28x28, you should have a 25000 x 28 x 28 matrix that represents those examples. You'll have to create a function that selects a random subset of those. The shape of the matrix you return will be batch_size x 28 x 28.

**Comment by jonbruner** [comment]
Thanks Adit!
