### ISSUE TITLE
Not able to load pre-trained model

### ISSUE THREAD

**Issue by cdutr** [jonbruner/generative-adversarial-networks#5]
Error `Tensor name "g_b1/beta" not found in checkpoint files pretrained-model/pretrained_gan.ckpt` when loading pre-trained model, can anyone help?

**Comment by cdutr** [comment]
Apparently the pre-trained model did not use the beta variables (`g_b1`,  `g_b2` and `g_b3`), removing it from the generators definition it worked. 

Also, these variables are the constant coefficients, sou they should be initialized using `initializer=tf.constant_initializer(0)`.

**Comment by jonbruner** [comment]
Thanks for catching this. We added those beta variables in the most recent code revision two months ago, but must have forgotten to regenerate the pre-trained models. I'll try to regenerate them and upload in the next few days.

**Comment by Santosh-Gupta** [comment]
"I'll try to regenerate them and upload in the next few days."

Hello, were they ever uploaded? I am getting that error as well

Edit:

Actually I got it to work just by using the old version here

https://github.com/jonbruner/generative-adversarial-networks/blob/b3e0392f43e92724d32ea95684f83894065003d4/gan-notebook.ipynb

**Comment by jonbruner** [comment]
I've regenerated the pre-trained model and updated that directory in the repo; everything should work now. Thanks for your patience.
