### ISSUE TITLE
why  this code only in discriminator, but not in generator?: 

### ISSUE THREAD

**Issue by Arthurzhangsheng** [jonbruner/generative-adversarial-networks#7]
why  this code only in discriminator, but not in generator?: 
`with tf.variable_scope(tf.get_variable_scope(), reuse=reuse_variables) as scope:`

**Comment by jonbruner** [comment]
I don't remember fully without doing more research, but I think it has to do with the fact that the discriminator gets called through two different loss functions on every training cycle, `d_loss_real` and `d_loss_fake`, and needs to keep the same variable scope between them, whereas the generator only gets called through `g_loss`.

That said, I'm feeling rusty on this project as I glance back over it. Maybe @adeshpande3 remembers?
